---
# tasks file for kevensen.oc-project-migrator
- block:

  - name: Get Image Streams
    set_fact:
      image_stream: "{{ lookup('oc',
                               'ImageStream',
                               host=inventory_hostname,
                               token=hostvars[inventory_hostname]['ansible_sa_token'],
                               namespace=project_name,
                               resource_name=item,
                               validate_certs=validate_certs) }}"
    with_items: "{{ image_streams_to_migrate }}"
    register: image_streams

  - name: Import Images
    oc:
      state: present
      inline:
        kind: ImageStreamImport
        apiVersion: "{{ item.ansible_facts.image_stream.apiVersion }}"
        metadata:
          name: "{{ item.ansible_facts.image_stream.metadata.name }}"
          namespace: "{{ item.ansible_facts.image_stream.metadata.namespace }}"
        spec:
          import: true
          images:
          - to:
              name: latest
            from:
              kind: DockerImage
              name: "{{ item.ansible_facts.image_stream.spec.dockerImageRepository }}"
            importPolicy:
              insecure: "{{ insecure_image_streams }}"
      token: "{{ ansible_sa_token }}"
      validate_certs: "{{ validate_certs }}"
    with_items: "{{ image_streams.results }}"
  when: inventory_hostname != from_host
