---
# tasks file for kevensen.oc-project-migrator
- name: Get Image Streams
  oc:
    state: present
    kind: ImageStream
    name: "{{ item }}"
    namespace: "{{ project_name }}"
  register: image_streams
  with_items: "{{ image_streams_to_migrate }}"
  delegate_to: "{{ from_host }}"
  delegate_facts: True

- block:
  - name: Migrate Image Streams Different Clusters
    oc:
      state: present
      inline:
        kind: ImageStream
        apiVersion: "{{ item.ansible_facts.oc.result.apiVersion }}"
        metadata:
          name: "{{ item.ansible_facts.oc.result.metadata.name }}"
          namespace: "{{ dest_project_name }}"
          annotations: "{{ item.ansible_facts.oc.result.metadata.annotations }}"
          labels: "{{ item.ansible_facts.oc.result.metadata.labels }}"
        spec:
          dockerImageRepository: "{{ registry_route_hostname }}/{{ item.ansible_facts.oc.result.metadata.namespace }}/{{ item.ansible_facts.oc.result.metadata.name }}"
    with_items: "{{ image_streams.results }}"

  - name: Configure Insecure ImageStreams
    oc:
      state: present
      inline:
        kind: ImageStream
        apiVersion: "{{ item.ansible_facts.oc.result.apiVersion }}"
        metadata:
          name: "{{ item.ansible_facts.oc.result.metadata.name }}"
          namespace: "{{ dest_project_name }}"
          annotations:
            openshift.io/image.insecureRepository: "true"
    when: insecure_image_streams
    with_items: "{{ image_streams.results }}"

  when: inventory_hostname != from_host



- name: Migrate Image Streams Same Cluster
  oc:
    state: present
    inline:
      kind: ImageStream
      apiVersion: "{{ item.ansible_facts.oc.result.apiVersion }}"
      metadata:
        name: "{{ item.ansible_facts.oc.result.metadata.name }}"
        namespace: "{{ dest_project_name }}"
        annotations: "{{ item.ansible_facts.oc.result.metadata.annotations }}"
        labels: "{{ item.ansible_facts.oc.result.metadata.labels }}"
      spec:
        dockerImageRepository: "{{ item.ansible_facts.oc.result.status.dockerImageRepository }}"
  with_items: "{{ image_streams.results }}"
  when: inventory_hostname == from_host
