---
- name: Get Project {{ project_name }}
  set_fact:
    source_project:  "{{ lookup('oc',
                                'Project',
                                host=from_host,
                                token=hostvars[from_host]['ansible_sa_token'],
                                resource_name=project_name,
                                validate_certs=validate_certs) }}"

- name: Migrate Project {{ project_name }}
  oc:
    state: present
    inline:
      kind: ProjectRequest
      metadata:
        name: "{{ source_project.metadata.name }}{{ project_name_postpend }}"
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"

- name: Set Project name
  set_fact:
    dest_project_name: "{{ source_project.metadata.name }}{{ project_name_postpend }}"
