---
- name: Get Routes
  set_fact:
    route: "{{ lookup('oc',
                      'Route',
                      host=from_host,
                      token=hostvars[from_host]['ansible_sa_token'],
                      namespace=project_name,
                      resource_name=item,
                      validate_certs=validate_certs) }}"
  with_items: "{{ routes_to_migrate }}"
  register: routes

- name: Migrate Routes
  oc:
    state: present
    inline:
      kind: "{{ item.ansible_facts.route.kind }}"
      apiVersion: "{{ item.ansible_facts.route.apiVersion }}"
      metadata:
        name: "{{ item.ansible_facts.route.metadata.name }}"
        namespace: "{{ dest_project_name }}"
        labels: "{{ item.ansible_facts.route.metadata.labels }}"
      spec:
        to: "{{ item.ansible_facts.route.spec.to }}"
        host: ''
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
  with_items: "{{ routes.results }}"

- name: Get Routes
  set_fact:
    route: "{{ lookup('oc',
                      'Route',
                      host=from_host,
                      token=hostvars[from_host]['ansible_sa_token'],
                      namespace='default',
                      resource_name='docker-registry',
                      validate_certs=validate_certs) }}"

- name: Set Registry Route Hostname
  set_fact:
    registry_route_hostname: "{{ route.spec.host }}"
