---
# tasks file for kevensen.oc-project-migrator
- name: Get Routes
  oc:
    state: present
    kind: Route
    name: "{{ item }}"
    namespace: "{{ project_name }}"
    validate_certs: "{{ validate_certs }}"
  register: routes
  with_items: "{{ routes_to_migrate }}"
  delegate_to: "{{ from_host }}"
  delegate_facts: True
#
- name: Migrate Routes
  oc:
    state: present
    inline:
      kind: "{{ item.ansible_facts.oc.result.kind }}"
      apiVersion: "{{ item.ansible_facts.oc.result.apiVersion }}"
      metadata:
        name: "{{ item.ansible_facts.oc.result.metadata.name }}"
        namespace: "{{ dest_project_name }}"
        labels: "{{ item.ansible_facts.oc.result.metadata.labels }}"
      spec:
        to: "{{ item.ansible_facts.oc.result.spec.to }}"
        host: ''
      validate_certs: "{{ validate_certs }}"
  with_items: "{{ routes.results }}"

- name: Get Container Registry Route
  oc:
    state: present
    kind: Route
    name: "{{ default_registry_route_name }}"
    namespace: default
    validate_certs: "{{ validate_certs }}"
  delegate_to: "{{ from_host }}"
  delegate_facts: True
  register: registry_route

- name: Set Registry Route Hostname
  set_fact:
    registry_route_hostname: "{{ registry_route.ansible_facts.oc.result.spec.host }}"
