---
- name: Get Secrets
  set_fact:
    secret: "{{ lookup('oc',
                       'Secret',
                       host=from_host,
                       token=hostvars[from_host]['ansible_sa_token'],
                       namespace=project_name,
                       resource_name=item,
                       validate_certs=validate_certs) }}"
  with_items: "{{ secrets_to_migrate }}"
  register: secrets


- name: Migrate Secrets
  oc:
    state: present
    namespace: "{{ dest_project_name }}"
    inline: "{{ item.ansible_facts.secret | uniqueify_resource }}"
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
  no_log: true
  with_items: "{{ secrets.results }}"
