---
# tasks file for kevensen.oc-project-migrator
- name: Get Secrets
  oc:
    state: present
    kind: Secret
    name: "{{ item }}"
    namespace: "{{ project_name }}"
    validate_certs: "{{ validate_certs }}"
  register: secrets
  with_items: "{{ secrets_to_migrate }}"
  delegate_to: "{{ from_host }}"
  delegate_facts: True

- name: Migrate Secrets
  oc:
    state: present
    namespace: "{{ dest_project_name }}"
    inline: "{{ item.ansible_facts.oc.result | uniqueify_resource }}"
    validate_certs: "{{ validate_certs }}"
  with_items: "{{ secrets.results }}"
