---
- name: Get Services
  set_fact:
    service: "{{ lookup('oc',
                        'Service',
                        host=from_host,
                        token=hostvars[from_host]['ansible_sa_token'],
                        namespace=project_name,
                        resource_name=item,
                        validate_certs=validate_certs) }}"
  with_items: "{{ services_to_migrate }}"
  register: services

- name: Migrate Services
  oc:
    state: present
    namespace: "{{ dest_project_name }}"
    inline: "{{ item.ansible_facts.service | uniqueify_resource }}"
    validate_certs: "{{ validate_certs }}"
    token: "{{ ansible_sa_token }}"
  with_items: "{{ services.results }}"

- name: Get Docker Registry Service
  set_fact:
    service: "{{ lookup('oc',
                        'Service',
                        host=from_host,
                        token=hostvars[from_host]['ansible_sa_token'],
                        namespace='default',
                        resource_name='docker-registry',
                        validate_certs=validate_certs) }}"

- name: Set Docker Registry Cluster IP
  set_fact:
    registry_cluster_ip: "{{ service.spec.clusterIP }}"
