---
# tasks file for kevensen.oc-project-migrator

- name: Get Service Accounts
  oc:
    state: present
    kind: ServiceAccount
    name: "{{ item }}"
    namespace: "{{ project_name }}"
  register: service_accounts
  with_items: "{{ service_accounts_to_migrate }}"
  delegate_to: "{{ from_host }}"
  delegate_facts: True

- name: Migrate Service Accounts
  oc:
    state: present
    namespace: "{{ dest_project_name }}"
    inline: "{{ item.ansible_facts.oc.result | uniqueify_resource }}"
  with_items: "{{ service_accounts.results }}"

- block:
  - name: Get Service Account Docker Configs
    oc:
      state: present
      kind: Secret
      namespace: "{{ project_name }}"
      fieldSelector: "type=kubernetes.io/dockercfg"
    register: tokens

  - name: Migrate Service Account Docker Configs
    oc:
      state: present
      inline:
        kind: Secret
        apiVersion: "{{ tokens.ansible_facts.oc.result.apiVersion }}"
        metadata:
          name: "{{ item['metadata']['name'] }}-{{ project_name }}"
          namespace: "{{ dest_project_name }}"
          annotations:
            kubernetes.io/service-account.name: "{{ item['metadata']['annotations']['kubernetes.io/service-account.name'] }}"
        data: "{{ item['data'] | base64decode | regex_replace }}"
        type: "{{ item['type'] }}"
    with_items: "{{ tokens.ansible_facts.oc.result.item_list }}"
  when: inventory_hostname != from_host

- name: Ensure service account has image-puller role from project "{{ dest_project_name }} to {{ project_name }}"
  oc:
    state: present
    inline:
      kind: RoleBinding
      metadata:
        name: "system:image-pullers"
        namespace: "{{ project_name }}"
      roleRef:
        name: "system:image-puller"
      groupNames:
      - "system:serviceaccounts:{{ project_name }}"
      - "system:serviceaccounts:{{ dest_project_name }}"
