---
# tasks file for kevensen.oc-project-migrator
- name: Get Services
  oc:
    state: present
    kind: Service
    name: "{{ item }}"
    namespace: "{{ project_name }}"
    validate_certs: "{{ validate_certs }}"
  register: services
  with_items: "{{ services_to_migrate }}"
  delegate_to: "{{ from_host }}"
  delegate_facts: True

- name: Migrate Services
  oc:
    state: present
    namespace: "{{ dest_project_name }}"
    inline: "{{ item.ansible_facts.oc.result | uniqueify_resource }}"
    validate_certs: "{{ validate_certs }}"
  with_items: "{{ services.results }}"

- name: Get Docker Registry Service
  oc:
    state: present
    namespace: default
    name: "{{ default_registry_service_name }}"
    kind: Service
    validate_certs: "{{ validate_certs }}"
  delegate_to: "{{ from_host }}"
  delegate_facts: True
  register: registry_service

- name: Set Docker Registry Cluster IP
  set_fact:
    registry_cluster_ip: "{{ registry_service.ansible_facts.oc.result.spec.clusterIP }}"
